export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_TODO_LIST = "GET_TODO_LIST";
export const GET_TODO_LIST_SUCCESS = "GET_TODO_LIST_SUCCESS";
export const GET_TODO_LIST_ERROR = "GET_TODO_LIST_ERROR";

export const GET_TODO_COUNT = "GET_TODO_COUNT";
export const GET_TODO_COUNT_SUCCESS = "GET_TODO_COUNT_SUCCESS";
export const GET_TODO_COUNT_ERROR = "GET_TODO_COUNT_ERROR";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const DELETE_TODO_LIST = "DELETE_TODO_LIST_LIST";
export const DELETE_TODO_LIST_SUCCESS = "DELETE_TODO_LIST_SUCCESS";
export const DELETE_TODO_LIST_ERROR = "DELETE_TODO_LIST_ERROR";

export const UPDATE_TODO_LIST = "UPDATE_TODO_LIST";
export const UPDATE_TODO_LIST_SUCCESS = "UPDATE_TODO_LIST_SUCCESS";
export const UPDATE_TODO_LIST_ERROR = "UPDATE_TODO_LIST_ERROR";

export const SHOW_HIDE_MODAL = "SHOW_HIDE_MODAL";
